[workspace]
resolver = "2"
members = [
    "crates/fylge-core",
    "crates/fylge-db",
    "crates/fylge-replication",
    "crates/fylge-server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
