[package]
name = "fylge-db"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fylge-core = { path = "../fylge-core" }
redb = "2"
serde_json = "1"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tempfile = "3"
